apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: hello-world-eks
  region: us-east-1

iam:
  serviceRoleARN: "arn:aws:iam::1111111111:role/eks-cluster-role"

vpc:
  subnets:
    private:
      us-east-1a: { id: subnet-00000000000000000 }
      us-east-1b: { id: subnet-00000000000000000 }

addons:
  - name: cluster-auto-scaler
    wellKnownPolicies:
      autoScaler: true

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: t3.small
    minSize: 1
    maxSize: 10
    desiredCapacity: 3
    privateNetworking: true
    volumeSize: 20
