apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: hello-world
  name: my-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-helloworldcontainer
  minReplicas: 5
  maxReplicas: 200
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70